apiVersion: ray.io/v1
kind: RayService
metadata:
  name: gpt-oss-120-deploy
  namespace: default
spec:
  serveConfigV2: |
    applications:
    - name: gpt-oss-120
      route_prefix: /
      import_path: ray.serve.llm:build_openai_app
      args:
        llm_configs:
          - model_loading_config:
              model_id: gpt-oss-120b
              model_name: openai/gpt-oss-120b
            engine_kwargs:
              dtype: float32
              device: auto
              max_model_length: 1024
              gpu_memory_utilization: 0.8
            deployment_config:
              autoscaling_config:
                minReplicas: 1
                maxReplicas: 4
                target_ongoing_requests: 64
              max_ongoing_requests: 128
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          nodeSelector:
            workload: ray
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.33.0.914af0-py311
            resources:
              limits:
                cpu: "8"
                memory: "16Gi"
              requests:
                cpu: "8"
                memory: "16Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hf-token-secret                  
          tolerations:
            - effect: NoSchedule
              key: workload
              operator: Equal
              value: ray
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          nodeSelector:
            workload: ray
          containers:
          - name: llm
            image: rayproject/ray-ml:2.33.0.914af0-py311
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hf-token-secret
            resources:
              limits:
                nvidia.com/gpu: "2"
          tolerations:
            - effect: NoSchedule
              key: workload
              operator: Equal
              value: gpu