apiVersion: ray.io/v1
kind: RayService
metadata:
  name: gpt-oss-120-deploy
spec:
  serveConfigV2: |
    applications:
    - name: llm
      route_prefix: /
      import_path:  ray-operator.config.samples.vllm.serve:model
      deployments:
      - name: VLLMDeployment
        num_replicas: 1
      runtime_env:
        working_dir: "https://github.com/ray-project/kuberay/archive/master.zip"
        pip: ["vllm==0.10.1+gptoss --extra-index-url https://wheels.vllm.ai/gpt-oss/  --extra-index-url https://download.pytorch.org/whl/nightly/cu128 --index-strategy unsafe-best-match"]
        env_vars:
          MODEL_ID: "openai/gpt-oss-20b"
          TENSOR_PARALLELISM: "2"
          PIPELINE_PARALLELISM: "1"
  rayClusterConfig:
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          nodeSelector:
            purpose: ray-head
          containers:
          - name: ray-head
            image: rayproject/ray-ml:2.33.0.914af0-py311
            resources:
              limits:
                cpu: "8"
                memory: "16Gi"
              requests:
                cpu: "8"
                memory: "16Gi"
            ports:
            - containerPort: 6379
              name: gcs-server
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hf-token-secret                  
          tolerations:
            - effect: NoSchedule
              key: sku
              operator: Equal
              value: ray
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 4
      groupName: gpu-group
      rayStartParams: {}
      template:
        spec:
          nodeSelector:
            purpose: llama-demo
          containers:
          - name: llm
            image: rayproject/ray-ml:2.33.0.914af0-py311
            env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: hf-token-secret
            resources:
              limits:
                nvidia.com/gpu: "4"
              requests:
                nvidia.com/gpu: "4"
          # Please add the following taints to the GPU node.
          tolerations:
            - effect: NoSchedule
              key: sku
              operator: Equal
              value: gpu